apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-{{ $.Values.env.stoomlinkEnv }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  # Using do-block-storage instead of nfs
  # We need RWO support
  storageClassName: do-block-storage
