{{- range $key, $val := .Values.assetsDownloader }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $key }}-{{ $.Values.env.stoomlinkEnv }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: do-block-storage
{{- end }}
