apiVersion: v1
kind: Service
metadata:
  name: apm-es
  labels:
    app: apm-es
spec:
  selector:
    app: apm-es
  ports:
    - protocol: TCP
      port: 8200
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apm-es
  name: apm-es
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: apm-es
  template:
    metadata:
      labels:
        app: apm-es
    spec:
      imagePullSecrets:
        - name: registry-docker-io-nextmoov
      containers:
        - image: docker.elastic.co/apm/apm-server:7.12.1
          imagePullPolicy: Always
          name: apm-es
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: apm-es-configmap
              mountPath: "/usr/share/apm-server/apm-server.yml"
              subPath: apm-server.yml
      restartPolicy: Always
      volumes:
        - name: apm-es-configmap
          configMap:
            name: apm-es-configmap


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-es-configmap
data:
  apm-server.yml: |
    apm-server:
      # host: "localhost:8200"
      host: "0.0.0.0:8200"
      rum:
        enabled: true
    output:
      elasticsearch:
        hosts: {{ $.Values.env.elasticUrl | quote }}
    queue.mem.events: 4096
    max_procs: 1
