{{- range $key, $val := .Values.webapis }}
---
# apiVersion: networking.k8s.io/v1beta1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $key }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ $key }}.{{ $.Values.apiIngress.subdomain }}.{{ $.Values.env.stoomlinkEnv }}.{{ $.Values.apiIngress.host }}
    # Must be unique
    secretName: {{ $key }}.{{ $.Values.apiIngress.subdomain }}.{{ $.Values.env.stoomlinkEnv }}.{{ $.Values.apiIngress.host }}-tls-uniq-secret
  rules:
  - host: {{ $key }}.{{ $.Values.apiIngress.subdomain }}.{{ $.Values.env.stoomlinkEnv }}.{{ $.Values.apiIngress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ $key }}
          servicePort: {{ $.Values.service.port }}
{{- end }}
