nodeEnv: production
name: stoomlink-devcontainer-base
deployment:
  name: stoomlink-devcontainer-base
service:
  port: 80

# apps:
#   - client1

services:
  - server2
  # - root
  # - journey-planner

# client:
#   root:
#     imageSuffix:
#     value: foo1
#   journey-planner:
#     imageSuffix: -journey-planner
#     value: bar2

ssr:
  app:
    imageSuffix:
  smop4bike:
    imageSuffix: -smop4bike

# api:
#   search:
#     imageSuffix:
#     value: foo1
#   postgraphile:
#     imageSuffix: -journey-planner
#     value: bar2


# appConfig:
#   foo: bar

servicesConfig:
  - server1:
    foo: bar
  - server2: bar
    foo: bafoo


resources:
  requests:
    memory: "128Mi"
    cpu: ".5"
  limits:
    memory: "256Mi"
    cpu: ".5"

image:
  tag: 0.14.10-rc.0
  name: stoomlink-devcontainer-base
  owner: nextmoov
# nextmoov/stoomlink-devcontainer-base:0.14.10-rc.0

client-image:
  tag: 0.14.10-rc.0
  name: stoomlink-devcontainer-base-client
  owner: nextmoov

ingress:
  enabled: true
  host: stoomlink.io
  # subdomain: schema.ing-pip
  subdomain: web

secrets:
  dockerRegistry: registry-docker-io-nextmoov

env:
  nodeEnv: "production"
  stoomlinkEnv: "playground"
  pgConnectionString: "postgis://usr:pwd@postgis:5432"
  sentryDsn: "https://00000000000000000000000000000000@x000000.ingest.sentry.io/0000000"
  # clients env: NO SECRETS!!!!!!
clientEnv:
  reactAppSearch: "search.stoomlink.io"
  reactAppOtpUrl: "otp.stoomlink.io"
  reactAppPostgraphileUrl: "postgraphile.stoomlink.io/graphql"


          # - name: REACT_APP_SEARCH_URL
          #   value: "https://search.stoomlink.io"
          # - name: REACT_APP_OTP_HOST
          #   value: "https://otp.stoomlink.io"
          # - name: REACT_APP_POSTGRAPHILE_URL
          #   value: "https://playground.postgraphile.stoomlink.io/graphql"
