{{- range $key, $val := .Values.webapps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $key }}
  name: {{ $key }}
spec:
  replicas: 1
  strategy:
    # rollingUpdate:
    #   maxSurge: 25%
    #   maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
    spec:
      imagePullSecrets:
      - name: {{ $.Values.secrets.dockerRegistry }}
      containers:
      # - image: {{ $.Values.image.owner }}/{{ $.Values.image.name }}:{{ $.Values.image.tag }}
      - image: {{ $.Values.image.owner }}/{{ $.Values.image.name }}{{ $val.imageSuffix }}:{{ $.Values.image.tag }}
        imagePullPolicy: Always
        name: {{ $key }}
        resources:
          requests:
            memory: {{ $.Values.resources.requests.memory | quote }}
            cpu: {{ $.Values.resources.requests.cpu | quote }}
          limits:
            memory: {{ $.Values.resources.limits.memory | quote }}
            cpu: {{ $.Values.resources.limits.cpu | quote }}
        env:
          - name: STOOMLINK_APP
            value: {{ $key | quote }}
          - name: PORT
            value: {{ $.Values.service.port | quote }}
          - name: NODE_ENV
            value: {{ $.Values.env.nodeEnv | quote }}
          # - name: STOOMLINK_MODULE
          #   value: {{ $key | quote }}
          - name: STOOMLINK_ENV
            value: {{ $.Values.env.stoomlinkEnv | quote }}
          - name: SENTRY_DSN
            value: {{ $.Values.env.sentryDsn | quote }}
          - name: REACT_APP_SEARCH_URL
            value: "https://{{ $.Values.env.stoomlinkEnv }}.{{ $.Values.clientEnv.reactAppSearch }}"
          - name: REACT_APP_OTP_HOST
            value: "https://{{ $.Values.env.stoomlinkEnv }}.{{ $.Values.clientEnv.reactAppOtpUrl }}"
          - name: REACT_APP_POSTGRAPHILE_URL
            value: "https://{{ $.Values.env.stoomlinkEnv }}.{{ $.Values.clientEnv.reactAppPostgraphileUrl }}"
        ports:
          - containerPort: {{ $.Values.service.port }}
        readinessProbe:
          httpGet:
            path: /k8s-probe
            port: {{ $.Values.service.port }}
            scheme: HTTP
          initialDelaySeconds: 10 # Allow up to 1min to initially load
      restartPolicy: Always
{{- end }}

