{{- range $key, $val := .Values.assetsDownloader }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $key }}
  name: {{ $key }}
spec:
  replicas: 1
  strategy:
    # rollingUpdate:
    #   maxSurge: 25%
    #   maxUnavailable: 0
    type: Recreate
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
    spec:
      imagePullSecrets:
      - name: {{ $.Values.secrets.dockerRegistry }}
      containers:
      - image: {{ $.Values.image.owner }}/{{ $.Values.image.name }}:{{ $.Values.image.tag }}
        imagePullPolicy: Always
        name: {{ $key }}
        resources:
          requests:
            memory: {{ $.Values.resources.requests.memory | quote }}
            cpu: {{ $.Values.resources.requests.cpu | quote }}
          limits:
            memory: {{ $.Values.resources.limits.memory | quote }}
            cpu: {{ $.Values.resources.limits.cpu | quote }}
        env:
          # - name: STOOMLINK_APP
          #   value: {{ $key | quote }}
          - name: PORT
            value: {{ $.Values.service.port | quote }}
          - name: NODE_ENV
            value: {{ $.Values.env.nodeEnv | quote }}
          - name: STOOMLINK_MODULE
            value: {{ $key | quote }}
          - name: STOOMLINK_ENV
            value: {{ $.Values.env.stoomlinkEnv | quote }}
          - name: SENTRY_DSN
            value: {{ $.Values.env.sentryDsn | quote }}
          - name: KAFKA_URL
            value: "{{ $.Values.env.stoomlinkEnv }}-{{ $.Values.env.kafkaUrl }}"
          - name: APM_SERVER_HOST
            value: {{ $.Values.env.apmServerHost | quote }}
          {{- range $k, $value := $val.env }}
          - name: {{ $k }}
            value: {{ $value | quote }}
          {{- end }}
        volumeMounts:
          - mountPath: "/data"
            name: data
        ports:
          - containerPort: {{ $.Values.service.port }}
        readinessProbe:
          httpGet:
            path: /k8s-probe
            port: {{ $.Values.service.port }}
            scheme: HTTP
          initialDelaySeconds: 10 # Allow up to 1min to initially load
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ $key }}-{{ $.Values.env.stoomlinkEnv }}-data
{{- end }}

