apiVersion: v1
kind: Service
metadata:
  name: storage-postgis-{{ $.Values.env.stoomlinkEnv }}
  labels:
    app: storage-postgis-{{ $.Values.env.stoomlinkEnv }}
spec:
  selector:
    app: storage-postgis-{{ $.Values.env.stoomlinkEnv }}
  ports:
    - protocol: TCP
      port: 5432
---


kind: Service
apiVersion: v1
metadata:
  name: storage-postgis-{{ $.Values.env.stoomlinkEnv }}-external
  annotations:
    external-dns.alpha.kubernetes.io/hostname:  pg-{{ $.Values.env.stoomlinkEnv }}.{{ $.Values.ingress.subdomain }}.{{ $.Values.ingress.host }}
spec:
  type: NodePort
  selector:
    app: storage-postgis-{{ $.Values.env.stoomlinkEnv }}
  ports:
    - port: 27017
      # NodePort
      #
      # Supported Values : 30000-32767
      # Should be different from any other services, to avoid spreading workload across Nodes
      # One given port is available only once per host Node.
      # nodePort: 30029
  {{- range $key, $value := .Values.nodeportPg }}
    {{- if eq $key $.Values.env.stoomlinkEnv }}
      nodePort: {{ $value }}
    {{- end }}
  {{- end }}
      name: storage-postgis-{{ $.Values.env.stoomlinkEnv }}-port
