kind: Service
apiVersion: v1
metadata:
  name: mongo-db-{{ $.Values.env.stoomlinkEnv }}
spec:
  clusterIP: None
  selector:
    app: mongo-db-{{ $.Values.env.stoomlinkEnv }}
  ports:
    - port: 27017
      name: mongo-db-{{ $.Values.env.stoomlinkEnv }}

---

kind: Service
apiVersion: v1
metadata:
  name: mongo-db-{{ $.Values.env.stoomlinkEnv }}-external
  annotations:
    external-dns.alpha.kubernetes.io/hostname:  {{ $.Values.env.stoomlinkEnv }}.{{ $.Values.ingress.subdomain }}.{{ $.Values.ingress.host }}
spec:
  type: NodePort
  selector:
    app: mongo-db-{{ $.Values.env.stoomlinkEnv }}
  ports:
    - port: 27017
      # NodePort
      #
      # Supported Values : 30000-32767
      # Should be different from any other services, to avoid spreading workload across Nodes
      # One given port is available only once per host Node.
      # nodePort: 30029
  {{- range $key, $value := .Values.nodeport }}
    {{- if eq $key $.Values.env.stoomlinkEnv }}
      nodePort: {{ $value }}
    {{- end }}
  {{- end }}

      name: mongo-db-{{ $.Values.env.stoomlinkEnv }}-port
