{{- with .Values.servicesConfig }}
  {{- range $.Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ . }}
  labels:
    app: {{ . }}
spec:
  selector:
    app: {{ . }}
  ports:
    - protocol: TCP
      port: {{ $.Values.service.port  }}
  {{- end }}
{{- end }}

