nodeEnv: production
name: stoomlink-ingestion
deployment:
  name: stoomlink-ingestion
service:
  port: 80

connectors:
  gtfs-nmbs:
    moduleName: gtfs-nmbs


image:
  tag: 0.14.12-rc.12
  name: stoomlink-devcontainer-base-backend
  owner: nextmoov


resources:
  requests:
    memory: "128Mi"
    cpu: ".5"
  limits:
    memory: "200Mi"
    cpu: ".5"

ingress:
  enabled: true
  host: stoomlink.io
  # subdomain: schema.ing-pip
  subdomain: ingestion


secrets:
  dockerRegistry: registry-docker-io-nextmoov

env:
  nodeEnv: "production"
  stoomlinkEnv: "playground"
  pgConnectionString: "postgis://usr:pwd@postgis:5432"
  sentryDsn: "https://00000000000000000000000000000000@x000000.ingest.sentry.io/0000000"
  # clients env: NO SECRETS!!!!!!
clientEnv:
  reactAppSearch: "search.stoomlink.io"
  reactAppOtpUrl: "otp.stoomlink.io"
  reactAppPostgraphileUrl: "postgraphile.stoomlink.io/graphql"
