nodeEnv: production
name: stoomlink-schema
deployment:
  name: stoomlink-schema
service:
  port: 80

setup:
  schema:
    moduleName: schema

producer:
  foo: true


image:
  tag: 0.14.12-rc.42
  name: stoomlink-devcontainer-base-backend
  owner: nextmoov


resources:
  requests:
    memory: "128Mi"
    cpu: ".5"
  limits:
    memory: "200Mi"
    cpu: ".5"

ingress:
  enabled: true
  host: stoomlink.io
  subdomain: schema


secrets:
  dockerRegistry: registry-docker-io-nextmoov

env:
  nodeEnv: "production"
  stoomlinkEnv: "playground"
  # pgConnectionString: "postgis://gis:gis@storage-postgis-{{ $.Values.env.stoomlinkEnv }}:5432"
  pgConnectionString: "postgis://gis:gis@storage-postgis"
  # kafkaUrl: "ingestion-storage-staging-cp-kafka:9092"
  kafkaUrl: "ingestion-storage-cp-kafka:9092"
  sentryDsn: "https://00000000000000000000000000000000@x000000.ingest.sentry.io/0000000"
