
{{- with .Values.servicesConfig }}
  {{- range $.Values.apps }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ $.Values.env.stoomlinkEnv }}.{{ . }}.{{ $.Values.ingress.subdomain }}.{{ $.Values.ingress.host }}
    # Must be unique
    secretName: {{ . }}-devc-{{ $.Values.env.stoomlinkEnv }}-tls
  rules:
  - host: {{ $.Values.env.stoomlinkEnv }}.{{ . }}.{{ $.Values.ingress.subdomain }}.{{ $.Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ . }}
          servicePort: {{ $.Values.service.port }}
  {{- end }}
{{- end }}
