# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: storage-postgis2-playground-data
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 32Gi
#   storageClassName: do-block-storage
