{{- range $key, $val := .Values.otp }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  labels:
    app: {{ $key }}
spec:
  selector:
    app: {{ $key }}
  ports:
    - protocol: TCP
      port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.service.otpPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}-backend
  labels:
    app: {{ $key }}-backend
spec:
  selector:
    app: {{ $key }}
  ports:
    - protocol: TCP
      port: {{ $.Values.service.port }}
{{- end }}

